// World Cup 2026 — group stage fixtures (all 72 matches)
// Source: official FIFA draw / ESPN schedule. Dates are local match-day dates.
// Each match: id, group, date (YYYY-MM-DD), home, away.
// Picks lock at the start (local midnight) of the match's date — see app.js LOCK logic.

const FLAGS = {
  "Mexico": "🇲🇽", "South Africa": "🇿🇦", "South Korea": "🇰🇷", "Czechia": "🇨🇿",
  "Canada": "🇨🇦", "Bosnia and Herzegovina": "🇧🇦", "Qatar": "🇶🇦", "Switzerland": "🇨🇭",
  "Brazil": "🇧🇷", "Morocco": "🇲🇦", "Haiti": "🇭🇹", "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "United States": "🇺🇸", "Paraguay": "🇵🇾", "Australia": "🇦🇺", "Türkiye": "🇹🇷",
  "Germany": "🇩🇪", "Curaçao": "🇨🇼", "Ivory Coast": "🇨🇮", "Ecuador": "🇪🇨",
  "Netherlands": "🇳🇱", "Japan": "🇯🇵", "Sweden": "🇸🇪", "Tunisia": "🇹🇳",
  "Belgium": "🇧🇪", "Egypt": "🇪🇬", "Iran": "🇮🇷", "New Zealand": "🇳🇿",
  "Spain": "🇪🇸", "Cape Verde": "🇨🇻", "Saudi Arabia": "🇸🇦", "Uruguay": "🇺🇾",
  "France": "🇫🇷", "Senegal": "🇸🇳", "Iraq": "🇮🇶", "Norway": "🇳🇴",
  "Argentina": "🇦🇷", "Algeria": "🇩🇿", "Austria": "🇦🇹", "Jordan": "🇯🇴",
  "Portugal": "🇵🇹", "DR Congo": "🇨🇩", "Uzbekistan": "🇺🇿", "Colombia": "🇨🇴",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Croatia": "🇭🇷", "Ghana": "🇬🇭", "Panama": "🇵🇦"
};

const MATCHES = [
  { id: "m01", group: "A", date: "2026-06-11", home: "Mexico", away: "South Africa" },
  { id: "m02", group: "A", date: "2026-06-11", home: "South Korea", away: "Czechia" },
  { id: "m03", group: "B", date: "2026-06-12", home: "Canada", away: "Bosnia and Herzegovina" },
  { id: "m04", group: "D", date: "2026-06-12", home: "United States", away: "Paraguay" },
  { id: "m05", group: "B", date: "2026-06-13", home: "Qatar", away: "Switzerland" },
  { id: "m06", group: "C", date: "2026-06-13", home: "Brazil", away: "Morocco" },
  { id: "m07", group: "C", date: "2026-06-13", home: "Haiti", away: "Scotland" },
  { id: "m08", group: "D", date: "2026-06-13", home: "Australia", away: "Türkiye" },
  { id: "m09", group: "E", date: "2026-06-14", home: "Germany", away: "Curaçao" },
  { id: "m10", group: "F", date: "2026-06-14", home: "Netherlands", away: "Japan" },
  { id: "m11", group: "E", date: "2026-06-14", home: "Ivory Coast", away: "Ecuador" },
  { id: "m12", group: "F", date: "2026-06-14", home: "Sweden", away: "Tunisia" },
  { id: "m13", group: "H", date: "2026-06-15", home: "Spain", away: "Cape Verde" },
  { id: "m14", group: "G", date: "2026-06-15", home: "Belgium", away: "Egypt" },
  { id: "m15", group: "H", date: "2026-06-15", home: "Saudi Arabia", away: "Uruguay" },
  { id: "m16", group: "G", date: "2026-06-15", home: "Iran", away: "New Zealand" },
  { id: "m17", group: "I", date: "2026-06-16", home: "France", away: "Senegal" },
  { id: "m18", group: "I", date: "2026-06-16", home: "Iraq", away: "Norway" },
  { id: "m19", group: "J", date: "2026-06-16", home: "Argentina", away: "Algeria" },
  { id: "m20", group: "J", date: "2026-06-16", home: "Austria", away: "Jordan" },
  { id: "m21", group: "K", date: "2026-06-17", home: "Portugal", away: "DR Congo" },
  { id: "m22", group: "L", date: "2026-06-17", home: "England", away: "Croatia" },
  { id: "m23", group: "L", date: "2026-06-17", home: "Ghana", away: "Panama" },
  { id: "m24", group: "K", date: "2026-06-17", home: "Uzbekistan", away: "Colombia" },
  { id: "m25", group: "A", date: "2026-06-18", home: "Czechia", away: "South Africa" },
  { id: "m26", group: "B", date: "2026-06-18", home: "Switzerland", away: "Bosnia and Herzegovina" },
  { id: "m27", group: "B", date: "2026-06-18", home: "Canada", away: "Qatar" },
  { id: "m28", group: "A", date: "2026-06-18", home: "Mexico", away: "South Korea" },
  { id: "m29", group: "D", date: "2026-06-19", home: "United States", away: "Australia" },
  { id: "m30", group: "C", date: "2026-06-19", home: "Scotland", away: "Morocco" },
  { id: "m31", group: "C", date: "2026-06-19", home: "Brazil", away: "Haiti" },
  { id: "m32", group: "D", date: "2026-06-19", home: "Türkiye", away: "Paraguay" },
  { id: "m33", group: "F", date: "2026-06-20", home: "Netherlands", away: "Sweden" },
  { id: "m34", group: "E", date: "2026-06-20", home: "Germany", away: "Ivory Coast" },
  { id: "m35", group: "E", date: "2026-06-20", home: "Ecuador", away: "Curaçao" },
  { id: "m36", group: "F", date: "2026-06-20", home: "Tunisia", away: "Japan" },
  { id: "m37", group: "H", date: "2026-06-21", home: "Spain", away: "Saudi Arabia" },
  { id: "m38", group: "G", date: "2026-06-21", home: "Belgium", away: "Iran" },
  { id: "m39", group: "H", date: "2026-06-21", home: "Uruguay", away: "Cape Verde" },
  { id: "m40", group: "G", date: "2026-06-21", home: "New Zealand", away: "Egypt" },
  { id: "m41", group: "J", date: "2026-06-22", home: "Argentina", away: "Austria" },
  { id: "m42", group: "I", date: "2026-06-22", home: "France", away: "Iraq" },
  { id: "m43", group: "I", date: "2026-06-22", home: "Norway", away: "Senegal" },
  { id: "m44", group: "J", date: "2026-06-22", home: "Jordan", away: "Algeria" },
  { id: "m45", group: "K", date: "2026-06-23", home: "Portugal", away: "Uzbekistan" },
  { id: "m46", group: "L", date: "2026-06-23", home: "England", away: "Ghana" },
  { id: "m47", group: "L", date: "2026-06-23", home: "Panama", away: "Croatia" },
  { id: "m48", group: "K", date: "2026-06-23", home: "Colombia", away: "DR Congo" },
  { id: "m49", group: "B", date: "2026-06-24", home: "Switzerland", away: "Canada" },
  { id: "m50", group: "B", date: "2026-06-24", home: "Bosnia and Herzegovina", away: "Qatar" },
  { id: "m51", group: "C", date: "2026-06-24", home: "Scotland", away: "Brazil" },
  { id: "m52", group: "C", date: "2026-06-24", home: "Morocco", away: "Haiti" },
  { id: "m53", group: "A", date: "2026-06-24", home: "Czechia", away: "Mexico" },
  { id: "m54", group: "A", date: "2026-06-24", home: "South Africa", away: "South Korea" },
  { id: "m55", group: "E", date: "2026-06-25", home: "Ecuador", away: "Germany" },
  { id: "m56", group: "E", date: "2026-06-25", home: "Curaçao", away: "Ivory Coast" },
  { id: "m57", group: "F", date: "2026-06-25", home: "Japan", away: "Sweden" },
  { id: "m58", group: "F", date: "2026-06-25", home: "Tunisia", away: "Netherlands" },
  { id: "m59", group: "D", date: "2026-06-25", home: "Türkiye", away: "United States" },
  { id: "m60", group: "D", date: "2026-06-25", home: "Paraguay", away: "Australia" },
  { id: "m61", group: "I", date: "2026-06-26", home: "Norway", away: "France" },
  { id: "m62", group: "I", date: "2026-06-26", home: "Senegal", away: "Iraq" },
  { id: "m63", group: "H", date: "2026-06-26", home: "Cape Verde", away: "Saudi Arabia" },
  { id: "m64", group: "H", date: "2026-06-26", home: "Uruguay", away: "Spain" },
  { id: "m65", group: "G", date: "2026-06-26", home: "Egypt", away: "Iran" },
  { id: "m66", group: "G", date: "2026-06-26", home: "New Zealand", away: "Belgium" },
  { id: "m67", group: "L", date: "2026-06-27", home: "Panama", away: "England" },
  { id: "m68", group: "L", date: "2026-06-27", home: "Croatia", away: "Ghana" },
  { id: "m69", group: "K", date: "2026-06-27", home: "Colombia", away: "Portugal" },
  { id: "m70", group: "K", date: "2026-06-27", home: "DR Congo", away: "Uzbekistan" },
  { id: "m71", group: "J", date: "2026-06-27", home: "Algeria", away: "Austria" },
  { id: "m72", group: "J", date: "2026-06-27", home: "Jordan", away: "Argentina" }
];

// Knockout rounds get filled in AFTER the group stage (matchups depend on results).
// Leave empty for now — see README for how to unlock them.
const KNOCKOUT_MATCHES = [];

if (typeof module !== "undefined") { module.exports = { MATCHES, KNOCKOUT_MATCHES, FLAGS }; }
